### PR TITLE
feat: add string interpolation

### PR DESCRIPTION
**Pull request by jaschdoc**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Unless this is easy, its probably not worth the effort.

**Comment by jaschdoc** [comment]
Yeah I have no idea how this works, I feel like I've tried everything. Somehow it works on the scala website but not for us. I think I'll just remove the string delimiters we don't support in this PR.

**Comment by jaschdoc** [comment]
Works now

**Comment by magnus-madsen** [comment]
Neat!

**Pull request merged**
